assoc.h
NAME
assoc.h -
SYNOPSIS
Functions
void assoc_init (const int hashpower_init)
item * assoc_find (const char *key, const size_t nkey, const uint32_t hv)
int assoc_insert (item *item, const uint32_t hv)
void assoc_delete (const char *key, const size_t nkey, const uint32_t hv)
void do_assoc_move_next_bucket (void)
int start_assoc_maintenance_thread (void)
void stop_assoc_maintenance_thread (void)
Variables
unsigned int hashpower
Function Documentation
void assoc_init (const inthashpower_init)
References stats::hash_bytes, stats::hash_power_level, hashpower, hashsize, STATS_LOCK(), and STATS_UNLOCK().
Referenced by main().
item* assoc_find (const char *key, const size_tnkey, const uint32_thv)
References _stritem::h_next, hashmask, hashpower, ITEM_key, MEMCACHED_ASSOC_FIND, and _stritem::nkey.
Referenced by do_item_get().
int assoc_insert (item *item, const uint32_thv)
References _stritem::h_next, hashmask, hashpower, hashsize, ITEM_key, MEMCACHED_ASSOC_INSERT, and _stritem::nkey.
Referenced by do_item_link().
void assoc_delete (const char *key, const size_tnkey, const uint32_thv)
References _stritem::h_next, and MEMCACHED_ASSOC_DELETE.
Referenced by do_item_unlink(), and do_item_unlink_nolock().
void do_assoc_move_next_bucket (void)
int start_assoc_maintenance_thread (void)
References DEFAULT_HASH_BULK_MOVE.
Referenced by main().
void stop_assoc_maintenance_thread (void)
References cache_lock, and mutex_unlock.
Referenced by main().
Variable Documentation
unsigned int hashpower
Referenced by assoc_find(), assoc_init(), assoc_insert(), item_lock(), item_trylock(), and item_unlock().
Author
Generated automatically by Doxygen for memcached from the source code.