assoc.c
NAME
assoc.c -
SYNOPSIS
#include 'memcached.h'
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/signal.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <pthread.h>
Macros
#define hashsize(n) ((ub4)1<<(n))
#define hashmask(n) (hashsize(n)-1)
#define DEFAULT_HASH_BULK_MOVE 1
Typedefs
typedef unsigned long int ub4
typedef unsigned char ub1
Functions
void assoc_init (const int hashtable_init)
item * assoc_find (const char *key, const size_t nkey, const uint32_t hv)
int assoc_insert (item *it, const uint32_t hv)
void assoc_delete (const char *key, const size_t nkey, const uint32_t hv)
int start_assoc_maintenance_thread ()
void stop_assoc_maintenance_thread ()
Variables
unsigned int hashpower = HASHPOWER_DEFAULT
int hash_bulk_move = DEFAULT_HASH_BULK_MOVE
Macro Definition Documentation
#define hashsize(n) ((ub4)1<<(n))
Referenced by assoc_init(), and assoc_insert().
#define hashmask(n) (hashsize(n)-1)
Referenced by assoc_find(), and assoc_insert().
#define DEFAULT_HASH_BULK_MOVE 1
Referenced by start_assoc_maintenance_thread().
Typedef Documentation
typedef unsigned long int ub4
typedef unsigned char ub1
Function Documentation
void assoc_init (const inthashtable_init)
References stats::hash_bytes, stats::hash_power_level, hashpower, hashsize, STATS_LOCK(), and STATS_UNLOCK().
Referenced by main().
item* assoc_find (const char *key, const size_tnkey, const uint32_thv)
References _stritem::h_next, hashmask, hashpower, ITEM_key, MEMCACHED_ASSOC_FIND, and _stritem::nkey.
Referenced by do_item_get().
int assoc_insert (item *it, const uint32_thv)
References _stritem::h_next, hashmask, hashpower, hashsize, ITEM_key, MEMCACHED_ASSOC_INSERT, and _stritem::nkey.
Referenced by do_item_link().
void assoc_delete (const char *key, const size_tnkey, const uint32_thv)
References _stritem::h_next, and MEMCACHED_ASSOC_DELETE.
Referenced by do_item_unlink(), and do_item_unlink_nolock().
int start_assoc_maintenance_thread (void)
References DEFAULT_HASH_BULK_MOVE.
Referenced by main().
void stop_assoc_maintenance_thread (void)
References cache_lock, and mutex_unlock.
Referenced by main().
Variable Documentation
unsigned int hashpower = HASHPOWER_DEFAULT
Referenced by assoc_find(), assoc_init(), assoc_insert(), item_lock(), item_trylock(), and item_unlock().
int hash_bulk_move = DEFAULT_HASH_BULK_MOVE
Author
Generated automatically by Doxygen for memcached from the source code.