.TH "daemon.c" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
daemon.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'memcached\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdaemonize\fP (int nochdir, int noclose)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int daemonize (intnochdir, intnoclose)"

.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
