hash.h
NAME
hash.h -
SYNOPSIS
Functions
uint32_t hash (const void *key, size_t length, const uint32_t initval)
Function Documentation
uint32_t hash (const void *key, size_tlength, const uint32_tinitval)
Referenced by add_delta(), do_item_alloc(), do_item_flush_expired(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item().
Author
Generated automatically by Doxygen for memcached from the source code.