.TH "hash.h" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBhash\fP (const void *key, size_t length, const uint32_t initval)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t hash (const void *key, size_tlength, const uint32_tinitval)"

.PP
Referenced by add_delta(), do_item_alloc(), do_item_flush_expired(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
