items.c
NAME
items.c -
SYNOPSIS
#include 'memcached.h'
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/signal.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <assert.h>
Classes
struct itemstats_t
Macros
#define ITEM_UPDATE_INTERVAL 60
#define LARGEST_ID POWER_LARGEST
#define DEBUG_REFCNT(it, op) while(0)
Functions
void item_stats_reset (void)
uint64_t get_cas_id (void)
item * do_item_alloc (char *key, const size_t nkey, const int flags, const rel_time_t exptime, const int nbytes, const uint32_t cur_hv)
void item_free (item *it)
bool item_size_ok (const size_t nkey, const int flags, const int nbytes)
int do_item_link (item *it, const uint32_t hv)
void do_item_unlink (item *it, const uint32_t hv)
void do_item_unlink_nolock (item *it, const uint32_t hv)
void do_item_remove (item *it)
void do_item_update (item *it)
int do_item_replace (item *it, item *new_it, const uint32_t hv)
char * do_item_cachedump (const unsigned int slabs_clsid, const unsigned int limit, unsigned int *bytes)
void item_stats_evictions (uint64_t *evicted)
void do_item_stats_totals (ADD_STAT add_stats, void *c)
void do_item_stats (ADD_STAT add_stats, void *c)
void do_item_stats_sizes (ADD_STAT add_stats, void *c)
item * do_item_get (const char *key, const size_t nkey, const uint32_t hv)
item * do_item_touch (const char *key, size_t nkey, uint32_t exptime, const uint32_t hv)
void do_item_flush_expired (void)
Macro Definition Documentation
#define ITEM_UPDATE_INTERVAL 60
Referenced by do_item_update().
#define LARGEST_ID POWER_LARGEST
Referenced by do_item_flush_expired(), do_item_stats(), do_item_stats_sizes(), do_item_stats_totals(), and item_stats_evictions().
#define DEBUG_REFCNT(it, op) while(0)
Referenced by do_item_alloc(), do_item_get(), and item_free().
Function Documentation
void item_stats_reset (void)
References cache_lock, and mutex_unlock.
uint64_t get_cas_id (void)
Referenced by do_add_delta(), and do_item_link().
item* do_item_alloc (char *key, const size_tnkey, const intflags, const rel_time_texptime, const intnbytes, const uint32_tcur_hv)
References cache_lock, current_time, DEBUG_REFCNT, do_item_unlink_nolock(), settings::evict_to_free, itemstats_t::evicted, itemstats_t::evicted_nonzero, itemstats_t::evicted_time, itemstats_t::evicted_unfetched, itemstats_t::expired_unfetched, _stritem::exptime, _stritem::h_next, hash(), _stritem::it_flags, ITEM_CAS, ITEM_FETCHED, ITEM_key, ITEM_ntotal, ITEM_suffix, item_trylock(), item_trylock_unlock(), mutex_unlock, _stritem::nbytes, _stritem::next, _stritem::nkey, _stritem::nsuffix, settings::oldest_live, itemstats_t::outofmemory, _stritem::prev, itemstats_t::reclaimed, _stritem::refcount, refcount_decr(), refcount_incr(), settings::slab_automove, slabs_adjust_mem_requested(), slabs_alloc(), slabs_clsid(), _stritem::slabs_clsid, slabs_reassign(), TAIL_REPAIR_TIME, itemstats_t::tailrepairs, and settings::use_cas.
Referenced by do_add_delta(), do_store_item(), and item_alloc().
void item_free (item *it)
References DEBUG_REFCNT, _stritem::it_flags, ITEM_LINKED, ITEM_ntotal, _stritem::refcount, _stritem::slabs_clsid, and slabs_free().
Referenced by do_item_remove().
bool item_size_ok (const size_tnkey, const intflags, const intnbytes)
Returns true if an item will fit in the cache (its size does not exceed the maximum for a cache entry.)
References slabs_clsid(), and settings::use_cas.
int do_item_link (item *it, const uint32_thv)
References assoc_insert(), cache_lock, stats::curr_bytes, stats::curr_items, current_time, get_cas_id(), _stritem::it_flags, ITEM_key, ITEM_LINKED, ITEM_ntotal, ITEM_set_cas, ITEM_SLABBED, MEMCACHED_ITEM_LINK, mutex_unlock, _stritem::nbytes, _stritem::nkey, _stritem::refcount, refcount_incr(), STATS_LOCK(), STATS_UNLOCK(), _stritem::time, stats::total_items, and settings::use_cas.
Referenced by do_item_replace(), do_store_item(), and item_link().
void do_item_unlink (item *it, const uint32_thv)
may fail if transgresses limits
References assoc_delete(), cache_lock, stats::curr_bytes, stats::curr_items, do_item_remove(), _stritem::it_flags, ITEM_key, ITEM_LINKED, ITEM_ntotal, MEMCACHED_ITEM_UNLINK, mutex_unlock, _stritem::nbytes, _stritem::nkey, STATS_LOCK(), and STATS_UNLOCK().
Referenced by do_item_get(), do_item_replace(), and item_unlink().
void do_item_unlink_nolock (item *it, const uint32_thv)
References assoc_delete(), stats::curr_bytes, stats::curr_items, do_item_remove(), _stritem::it_flags, ITEM_key, ITEM_LINKED, ITEM_ntotal, MEMCACHED_ITEM_UNLINK, _stritem::nbytes, _stritem::nkey, STATS_LOCK(), and STATS_UNLOCK().
Referenced by do_item_alloc(), do_item_flush_expired(), and do_item_get().
void do_item_remove (item *it)
References _stritem::it_flags, item_free(), ITEM_key, ITEM_SLABBED, MEMCACHED_ITEM_REMOVE, _stritem::nbytes, _stritem::nkey, _stritem::refcount, and refcount_decr().
Referenced by do_add_delta(), do_item_get(), do_item_unlink(), do_item_unlink_nolock(), do_store_item(), and item_remove().
void do_item_update (item *it)
References cache_lock, current_time, _stritem::it_flags, ITEM_key, ITEM_LINKED, ITEM_SLABBED, ITEM_UPDATE_INTERVAL, MEMCACHED_ITEM_UPDATE, mutex_unlock, _stritem::nbytes, _stritem::nkey, and _stritem::time.
Referenced by do_add_delta(), do_store_item(), and item_update().
int do_item_replace (item *it, item *new_it, const uint32_thv)
update LRU time to current and reposition
References do_item_link(), do_item_unlink(), _stritem::it_flags, ITEM_key, ITEM_SLABBED, MEMCACHED_ITEM_REPLACE, _stritem::nbytes, and _stritem::nkey.
Referenced by item_replace().
char* do_item_cachedump (const unsigned intslabs_clsid, const unsigned intlimit, unsigned int *bytes)
References _stritem::exptime, ITEM_key, KEY_MAX_LENGTH, _stritem::nbytes, _stritem::next, _stritem::nkey, process_started, and slabs_clsid().
Referenced by item_cachedump().
void item_stats_evictions (uint64_t *evicted)
References cache_lock, itemstats_t::evicted, LARGEST_ID, and mutex_unlock.
void do_item_stats_totals (ADD_STATadd_stats, void *c)
References APPEND_STAT, itemstats_t::evicted, itemstats_t::evicted_unfetched, itemstats_t::expired_unfetched, LARGEST_ID, and itemstats_t::reclaimed.
Referenced by item_stats_totals().
void do_item_stats (ADD_STATadd_stats, void *c)
References APPEND_NUM_FMT_STAT, current_time, LARGEST_ID, STAT_KEY_LEN, and STAT_VAL_LEN.
Referenced by item_stats().
void do_item_stats_sizes (ADD_STATadd_stats, void *c)
dumps out a list of objects of each size, with granularity of 32 bytes
References APPEND_STAT, ITEM_ntotal, LARGEST_ID, and _stritem::next.
Referenced by item_stats_sizes().
item* do_item_get (const char *key, const size_tnkey, const uint32_thv)
wrapper around assoc_find which does the lazy expiration logic
References assoc_find(), current_time, DEBUG_REFCNT, do_item_remove(), do_item_unlink(), do_item_unlink_nolock(), _stritem::exptime, _stritem::it_flags, ITEM_FETCHED, ITEM_key, settings::oldest_live, _stritem::refcount, refcount_incr(), slab_rebalance::slab_end, slab_rebal, slab_rebalance_signal, slab_rebalance::slab_start, _stritem::time, and settings::verbose.
Referenced by do_add_delta(), do_item_touch(), do_store_item(), and item_get().
item* do_item_touch (const char *key, size_tnkey, uint32_texptime, const uint32_thv)
References do_item_get(), and _stritem::exptime.
Referenced by item_touch().
void do_item_flush_expired (void)
References do_item_unlink_nolock(), hash(), _stritem::it_flags, ITEM_key, ITEM_SLABBED, LARGEST_ID, _stritem::next, _stritem::nkey, settings::oldest_live, and _stritem::time.
Referenced by item_flush_expired().
Author
Generated automatically by Doxygen for memcached from the source code.