memcached.c
NAME
memcached.c -
SYNOPSIS
#include 'memcached.h'
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <signal.h>
#include <sys/resource.h>
#include <sys/uio.h>
#include <ctype.h>
#include <stdarg.h>
#include <pwd.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <assert.h>
#include <limits.h>
#include <sysexits.h>
#include <stddef.h>
Classes
struct token_s
Macros
#define _P1003_1B_VISIBLE
#define __need_IOV_MAX
#define REALTIME_MAXDELTA 60*60*24*30
#define COMMAND_TOKEN 0
#define SUBCOMMAND_TOKEN 1
#define KEY_TOKEN 1
#define MAX_TOKENS 8
Typedefs
typedef struct token_s token_t
Enumerations
enum try_read_result { READ_DATA_RECEIVED, READ_NO_DATA_RECEIVED, READ_ERROR, READ_MEMORY_ERROR }
enum transmit_result { TRANSMIT_COMPLETE, TRANSMIT_INCOMPLETE, TRANSMIT_SOFT_ERROR, TRANSMIT_HARD_ERROR }
Functions
conn * conn_from_freelist ()
bool conn_add_to_freelist (conn *c)
conn * conn_new (const int sfd, enum conn_states init_state, const int event_flags, const int read_buffer_size, enum network_transport transport, struct event_base *base)
enum store_item_type do_store_item (item *it, int comm, conn *c, const uint32_t hv)
void append_stat (const char *name, ADD_STAT add_stats, conn *c, const char *fmt,...)
enum delta_result_type do_add_delta (conn *c, const char *key, const size_t nkey, const bool incr, const int64_t delta, char *buf, uint64_t *cas, const uint32_t hv)
void do_accept_new_conns (const bool do_accept)
int main (int argc, char **argv)
Variables
struct stats stats
struct settings settings
time_t process_started
struct slab_rebalance slab_rebal
volatile int slab_rebalance_signal
volatile rel_time_t current_time
Macro Definition Documentation
#define _P1003_1B_VISIBLE
#define __need_IOV_MAX
#define REALTIME_MAXDELTA 60*60*24*30
#define COMMAND_TOKEN 0
#define SUBCOMMAND_TOKEN 1
#define KEY_TOKEN 1
#define MAX_TOKENS 8
Typedef Documentation
typedef struct token_s token_t
Enumeration Type Documentation
enum try_read_result
Enumerator
READ_DATA_RECEIVED
READ_NO_DATA_RECEIVED
READ_ERROR
READ_MEMORY_ERROR
an error occured (on the socket) (or client closed connection) failed to allocate more memory
enum transmit_result
Enumerator
TRANSMIT_COMPLETE
TRANSMIT_INCOMPLETE
All done writing.
TRANSMIT_SOFT_ERROR
More data remaining to write.
TRANSMIT_HARD_ERROR
Can't write any more right now. Can't write (c->state is set to conn_closing)
Function Documentation
conn* conn_from_freelist (void)
Referenced by conn_new().
bool conn_add_to_freelist (conn *c)
Referenced by conn_new().
conn* conn_new (const intsfd, enum conn_statesinit_state, const intevent_flags, const intread_buffer_size, enum network_transporttransport, struct event_base *base)
References ascii_prot, binary_prot, settings::binding_protocol, conn::cmd, conn_add_to_freelist(), conn_from_freelist(), conn_listening, stats::conn_structs, stats::curr_conns, DATA_BUFFER_SIZE, conn::ev_flags, conn::event, conn::hdrbuf, conn::hdrsize, conn::icurr, conn::ileft, conn::ilist, conn::iov, IOV_LIST_INITIAL, conn::iovsize, conn::iovused, IS_UDP, conn::isize, conn::item, ITEM_LIST_INITIAL, MEMCACHED_CONN_ALLOCATE, MEMCACHED_CONN_CREATE, MSG_LIST_INITIAL, conn::msgcurr, conn::msglist, conn::msgsize, conn::msgused, negotiating_prot, conn::noreply, conn::protocol, conn::rbuf, conn::rbytes, conn::rcurr, conn::request_addr, conn::request_addr_size, conn::ritem, conn::rlbytes, conn::rsize, conn::sfd, settings::socketpath, conn::state, STATS_LOCK(), STATS_UNLOCK(), SUFFIX_LIST_INITIAL, conn::suffixcurr, conn::suffixleft, conn::suffixlist, conn::suffixsize, stats::total_conns, conn::transport, settings::verbose, conn::wbuf, conn::wbytes, conn::wcurr, conn::write_and_free, conn::write_and_go, and conn::wsize.
enum store_item_type do_store_item (item *it, intcomm, conn *c, const uint32_thv)
References conn::cas, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, do_item_alloc(), do_item_get(), do_item_link(), do_item_remove(), do_item_update(), EXISTS, _stritem::exptime, ITEM_data, ITEM_get_cas, ITEM_key, item_replace(), ITEM_suffix, thread_stats::mutex, _stritem::nbytes, _stritem::nkey, NOT_FOUND, NOT_STORED, NREAD_ADD, NREAD_APPEND, NREAD_CAS, NREAD_PREPEND, NREAD_REPLACE, thread_stats::slab_stats, _stritem::slabs_clsid, LIBEVENT_THREAD::stats, STORED, conn::thread, and settings::verbose.
Referenced by store_item().
void append_stat (const char *name, ADD_STATadd_stats, conn *c, const char *fmt, ...)
References STAT_VAL_LEN.
enum delta_result_type do_add_delta (conn *c, const char *key, const size_tnkey, const boolincr, const int64_tdelta, char *buf, uint64_t *cas, const uint32_thv)
References cache_lock, slab_stats::decr_hits, DELTA_ITEM_CAS_MISMATCH, DELTA_ITEM_NOT_FOUND, do_item_alloc(), do_item_get(), do_item_remove(), do_item_update(), EOM, _stritem::exptime, get_cas_id(), slab_stats::incr_hits, INCR_MAX_STORAGE_LEN, ITEM_data, ITEM_get_cas, ITEM_key, item_replace(), ITEM_set_cas, ITEM_suffix, MEMCACHED_COMMAND_DECR, MEMCACHED_COMMAND_INCR, thread_stats::mutex, mutex_unlock, _stritem::nbytes, _stritem::nkey, NON_NUMERIC, OK, _stritem::refcount, safe_strtoull(), conn::sfd, thread_stats::slab_stats, _stritem::slabs_clsid, LIBEVENT_THREAD::stats, conn::thread, and settings::use_cas.
Referenced by add_delta().
void do_accept_new_conns (const booldo_accept)
References stats::accepting_conns, settings::backlog, stats::listen_disabled_num, conn::next, conn::sfd, STATS_LOCK(), and STATS_UNLOCK().
Referenced by accept_new_conns().
int main (intargc, char **argv)
References settings::access, ascii_prot, assoc_init(), settings::backlog, binary_prot, settings::binding_protocol, settings::chunk_size, stats::curr_conns, daemonize(), settings::detail_enabled, drop_privileges(), settings::evict_to_free, settings::factor, settings::hashpower_init, init_sasl(), settings::inter, settings::item_size_max, settings::maxbytes, settings::maxconns, settings::maxconns_fast, negotiating_prot, settings::num_threads, settings::num_threads_per_udp, settings::port, settings::prefix_delimiter, settings::reqs_per_event, stats::reserved_fds, settings::sasl, settings::slab_automove, settings::slab_reassign, slabs_init(), settings::socketpath, start_assoc_maintenance_thread(), start_slab_maintenance_thread(), stop_assoc_maintenance_thread(), tcp_transport, thread_init(), udp_transport, settings::udpport, settings::use_cas, settings::verbose, and vperror().
Variable Documentation
struct stats stats
exported globals
struct settings settings
time_t process_started
Referenced by do_item_cachedump().
struct slab_rebalance slab_rebal
Referenced by do_item_get(), and start_slab_maintenance_thread().
volatile int slab_rebalance_signal
Referenced by do_item_get(), and start_slab_maintenance_thread().
volatile rel_time_t current_time
Referenced by do_item_alloc(), do_item_get(), do_item_link(), do_item_stats(), and do_item_update().
Author
Generated automatically by Doxygen for memcached from the source code.