memcached.h
NAME
memcached.h -
SYNOPSIS
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <event.h>
#include <netdb.h>
#include <pthread.h>
#include <unistd.h>
#include 'protocol_binary.h'
#include 'cache.h'
#include 'sasl_defs.h'
#include 'stats.h'
#include 'slabs.h'
#include 'assoc.h'
#include 'items.h'
#include 'trace.h'
#include 'hash.h'
#include 'util.h'
Classes
struct slab_stats
struct thread_stats
struct stats
struct settings
struct _stritem
struct LIBEVENT_THREAD
struct LIBEVENT_DISPATCHER_THREAD
struct conn
struct slab_rebalance
Macros
#define KEY_MAX_LENGTH 250
#define INCR_MAX_STORAGE_LEN 24
#define DATA_BUFFER_SIZE 2048
#define UDP_READ_BUFFER_SIZE 65536
#define UDP_MAX_PAYLOAD_SIZE 1400
#define UDP_HEADER_SIZE 8
#define MAX_SENDBUF_SIZE (256 * 1024 * 1024)
#define SUFFIX_SIZE 24
#define ITEM_LIST_INITIAL 200
#define SUFFIX_LIST_INITIAL 20
#define IOV_LIST_INITIAL 400
#define MSG_LIST_INITIAL 10
#define READ_BUFFER_HIGHWAT 8192
#define ITEM_LIST_HIGHWAT 400
#define IOV_LIST_HIGHWAT 600
#define MSG_LIST_HIGHWAT 100
#define MIN_BIN_PKT_LENGTH 16
#define BIN_PKT_HDR_WORDS (MIN_BIN_PKT_LENGTH/sizeof(uint32_t))
#define HASHPOWER_DEFAULT 16
#define POWER_SMALLEST 1
#define POWER_LARGEST 200
#define CHUNK_ALIGN_BYTES 8
#define MAX_NUMBER_OF_SLAB_CLASSES (POWER_LARGEST + 1)
#define TAIL_REPAIR_TIME (3 * 3600)
#define ITEM_get_cas(i)
#define ITEM_set_cas(i, v)
#define ITEM_key(item)
#define ITEM_suffix(item)
#define ITEM_data(item)
#define ITEM_ntotal(item)
#define STAT_KEY_LEN 128
#define STAT_VAL_LEN 128
#define APPEND_STAT(name, fmt, val) append_stat(name, add_stats, c, fmt, val);
#define APPEND_NUM_FMT_STAT(name_fmt, num, name, fmt, val)
#define APPEND_NUM_STAT(num, name, fmt, val) APPEND_NUM_FMT_STAT('%d:%s', num, name, fmt, val)
#define IS_UDP(x) (x == udp_transport)
#define NREAD_ADD 1
#define NREAD_SET 2
#define NREAD_REPLACE 3
#define NREAD_APPEND 4
#define NREAD_PREPEND 5
#define NREAD_CAS 6
#define MAX_VERBOSITY_LEVEL 2
#define ITEM_LINKED 1
#define ITEM_CAS 2
#define ITEM_SLABBED 4
#define ITEM_FETCHED 8
#define mutex_unlock(x) pthread_mutex_unlock(x)
#define drop_privileges()
#define __builtin_expect(x, expected_value) (x)
#define likely(x) __builtin_expect((x),1)
#define unlikely(x) __builtin_expect((x),0)
Typedefs
typedef void(* ADD_STAT )(const char *key, const uint16_t klen, const char *val, const uint32_t vlen, const void *cookie)
typedef unsigned int rel_time_t
typedef struct _stritem item
typedef struct conn conn
Enumerations
enum conn_states { conn_listening, conn_new_cmd, conn_waiting, conn_read, conn_parse_cmd, conn_write, conn_nread, conn_swallow, conn_closing, conn_mwrite, conn_max_state }
enum bin_substates { bin_no_state, bin_reading_set_header, bin_reading_cas_header, bin_read_set_value, bin_reading_get_key, bin_reading_stat, bin_reading_del_header, bin_reading_incr_header, bin_read_flush_exptime, bin_reading_sasl_auth, bin_reading_sasl_auth_data, bin_reading_touch_key }
enum protocol { ascii_prot = 3, binary_prot, negotiating_prot }
enum network_transport { local_transport, tcp_transport, udp_transport }
enum item_lock_types { ITEM_LOCK_GRANULAR = 0, ITEM_LOCK_GLOBAL }
enum store_item_type { NOT_STORED =0, STORED, EXISTS, NOT_FOUND }
enum delta_result_type { OK, NON_NUMERIC, EOM, DELTA_ITEM_NOT_FOUND, DELTA_ITEM_CAS_MISMATCH }
Functions
void do_accept_new_conns (const bool do_accept)
enum delta_result_type do_add_delta (conn *c, const char *key, const size_t nkey, const bool incr, const int64_t delta, char *buf, uint64_t *cas, const uint32_t hv)
enum store_item_type do_store_item (item *item, int comm, conn *c, const uint32_t hv)
conn * conn_new (const int sfd, const enum conn_states init_state, const int event_flags, const int read_buffer_size, enum network_transport transport, struct event_base *base)
int daemonize (int nochdir, int noclose)
void thread_init (int nthreads, struct event_base *main_base)
int dispatch_event_add (int thread, conn *c)
void dispatch_conn_new (int sfd, enum conn_states init_state, int event_flags, int read_buffer_size, enum network_transport transport)
enum delta_result_type add_delta (conn *c, const char *key, const size_t nkey, const int incr, const int64_t delta, char *buf, uint64_t *cas)
void accept_new_conns (const bool do_accept)
conn * conn_from_freelist (void)
bool conn_add_to_freelist (conn *c)
int is_listen_thread (void)
item * item_alloc (char *key, size_t nkey, int flags, rel_time_t exptime, int nbytes)
char * item_cachedump (const unsigned int slabs_clsid, const unsigned int limit, unsigned int *bytes)
void item_flush_expired (void)
item * item_get (const char *key, const size_t nkey)
item * item_touch (const char *key, const size_t nkey, uint32_t exptime)
int item_link (item *it)
void item_remove (item *it)
int item_replace (item *it, item *new_it, const uint32_t hv)
void item_stats (ADD_STAT add_stats, void *c)
void item_stats_totals (ADD_STAT add_stats, void *c)
void item_stats_sizes (ADD_STAT add_stats, void *c)
void item_unlink (item *it)
void item_update (item *it)
void item_lock_global (void)
void item_unlock_global (void)
void item_lock (uint32_t hv)
void * item_trylock (uint32_t hv)
void item_trylock_unlock (void *arg)
void item_unlock (uint32_t hv)
void switch_item_lock_type (enum item_lock_types type)
unsigned short refcount_incr (unsigned short *refcount)
unsigned short refcount_decr (unsigned short *refcount)
void STATS_LOCK (void)
void STATS_UNLOCK (void)
void threadlocal_stats_reset (void)
void threadlocal_stats_aggregate (struct thread_stats *stats)
void slab_stats_aggregate (struct thread_stats *stats, struct slab_stats *out)
void append_stat (const char *name, ADD_STAT add_stats, conn *c, const char *fmt,...)
enum store_item_type store_item (item *item, int comm, conn *c)
Variables
struct stats stats
time_t process_started
struct settings settings
volatile rel_time_t current_time
volatile int slab_rebalance_signal
struct slab_rebalance slab_rebal
Detailed Description
The main memcached header holding commonly used data structures and function prototypes.
Macro Definition Documentation
#define KEY_MAX_LENGTH 250
Maximum length of a key.
Referenced by do_item_cachedump().
#define INCR_MAX_STORAGE_LEN 24
Size of an incr buf.
Referenced by do_add_delta().
#define DATA_BUFFER_SIZE 2048
Referenced by conn_new().
#define UDP_READ_BUFFER_SIZE 65536
#define UDP_MAX_PAYLOAD_SIZE 1400
#define UDP_HEADER_SIZE 8
#define MAX_SENDBUF_SIZE (256 * 1024 * 1024)
#define SUFFIX_SIZE 24
#define ITEM_LIST_INITIAL 200
Initial size of list of items being returned by 'get'.
Referenced by conn_new().
#define SUFFIX_LIST_INITIAL 20
Initial size of list of CAS suffixes appended to 'gets' lines.
Referenced by conn_new().
#define IOV_LIST_INITIAL 400
Initial size of the sendmsg() scatter/gather array.
Referenced by conn_new().
#define MSG_LIST_INITIAL 10
Initial number of sendmsg() argument structures to allocate.
Referenced by conn_new().
#define READ_BUFFER_HIGHWAT 8192
High water marks for buffer shrinking
#define ITEM_LIST_HIGHWAT 400
#define IOV_LIST_HIGHWAT 600
#define MSG_LIST_HIGHWAT 100
#define MIN_BIN_PKT_LENGTH 16
#define BIN_PKT_HDR_WORDS (MIN_BIN_PKT_LENGTH/sizeof(uint32_t))
#define HASHPOWER_DEFAULT 16
#define POWER_SMALLEST 1
Referenced by slabs_clsid(), and slabs_init().
#define POWER_LARGEST 200
Referenced by slabs_init().
#define CHUNK_ALIGN_BYTES 8
Referenced by slabs_init().
#define MAX_NUMBER_OF_SLAB_CLASSES (POWER_LARGEST + 1)
Referenced by slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset().
#define TAIL_REPAIR_TIME (3 * 3600)
How long an object can reasonably be assumed to be locked before harvesting it on a low memory condition.
Referenced by do_item_alloc().
#define ITEM_get_cas(i)
Value:
(((i)->it_flags & ITEM_CAS) ? \
        (i)->data->cas : (uint64_t)0)
Referenced by do_add_delta(), and do_store_item().
#define ITEM_set_cas(i, v)
Value:
{ \
    if ((i)->it_flags & ITEM_CAS) { \
        (i)->data->cas = v; \
    } \
}
Referenced by do_add_delta(), and do_item_link().
#define ITEM_key(item)
Value:
(((char*)&((item)->data)) \
         + (((item)->it_flags & ITEM_CAS) ? sizeof(uint64_t) : 0))
Referenced by assoc_find(), assoc_insert(), do_add_delta(), do_item_alloc(), do_item_cachedump(), do_item_flush_expired(), do_item_get(), do_item_link(), do_item_remove(), do_item_replace(), do_item_unlink(), do_item_unlink_nolock(), do_item_update(), do_store_item(), item_link(), item_remove(), item_unlink(), item_update(), and store_item().
#define ITEM_suffix(item)
Value:
((char*) &((item)->data) + (item)->nkey + 1 \
         + (((item)->it_flags & ITEM_CAS) ? sizeof(uint64_t) : 0))
Referenced by do_add_delta(), do_item_alloc(), and do_store_item().
#define ITEM_data(item)
Value:
((char*) &((item)->data) + (item)->nkey + 1 \
         + (item)->nsuffix \
         + (((item)->it_flags & ITEM_CAS) ? sizeof(uint64_t) : 0))
Referenced by do_add_delta(), and do_store_item().
#define ITEM_ntotal(item)
Value:
(sizeof(struct _stritem) + (item)->nkey + 1 \
         + (item)->nsuffix + (item)->nbytes \
         + (((item)->it_flags & ITEM_CAS) ? sizeof(uint64_t) : 0))
Referenced by do_item_alloc(), do_item_link(), do_item_stats_sizes(), do_item_unlink(), do_item_unlink_nolock(), and item_free().
#define STAT_KEY_LEN 128
Referenced by do_item_stats().
#define STAT_VAL_LEN 128
Referenced by append_stat(), and do_item_stats().
#define APPEND_STAT(name, fmt, val) append_stat(name, add_stats, c, fmt, val);
Append a simple stat with a stat name, value format and value
Referenced by do_item_stats_sizes(), do_item_stats_totals(), and get_stats().
#define APPEND_NUM_FMT_STAT(name_fmt, num, name, fmt, val)
Value:
klen = snprintf(key_str, STAT_KEY_LEN, name_fmt, num, name); \
    vlen = snprintf(val_str, STAT_VAL_LEN, fmt, val); \
    add_stats(key_str, klen, val_str, vlen, c);
Append an indexed stat with a stat name (with format), value format and value
Referenced by do_item_stats().
#define APPEND_NUM_STAT(num, name, fmt, val) APPEND_NUM_FMT_STAT('%d:%s', num, name, fmt, val)
Common APPEND_NUM_FMT_STAT format.
#define IS_UDP(x) (x == udp_transport)
Referenced by conn_new().
#define NREAD_ADD 1
Referenced by do_store_item().
#define NREAD_SET 2
#define NREAD_REPLACE 3
Referenced by do_store_item().
#define NREAD_APPEND 4
Referenced by do_store_item().
#define NREAD_PREPEND 5
Referenced by do_store_item().
#define NREAD_CAS 6
Referenced by do_store_item().
#define MAX_VERBOSITY_LEVEL 2
#define ITEM_LINKED 1
Referenced by do_item_link(), do_item_unlink(), do_item_unlink_nolock(), do_item_update(), and item_free().
#define ITEM_CAS 2
Referenced by do_item_alloc().
#define ITEM_SLABBED 4
Referenced by do_item_flush_expired(), do_item_link(), do_item_remove(), do_item_replace(), and do_item_update().
#define ITEM_FETCHED 8
Referenced by do_item_alloc(), and do_item_get().
#define mutex_unlock(x) pthread_mutex_unlock(x)
Referenced by do_add_delta(), do_item_alloc(), do_item_link(), do_item_unlink(), do_item_update(), item_cachedump(), item_flush_expired(), item_stats(), item_stats_evictions(), item_stats_reset(), item_stats_sizes(), item_stats_totals(), item_trylock_unlock(), item_unlock(), item_unlock_global(), refcount_decr(), refcount_incr(), and stop_assoc_maintenance_thread().
#define drop_privileges(void)
#define __builtin_expect(x, expected_value) (x)
#define likely(x) __builtin_expect((x),1)
Referenced by item_lock(), and item_unlock().
#define unlikely(x) __builtin_expect((x),0)
Typedef Documentation
typedef void(* ADD_STAT)(const char *key, const uint16_t klen, const char *val, const uint32_t vlen, const void *cookie)
Callback for any function producing stats.
Parameters:
key the stat's key
klen length of the key
val the stat's value in an ascii form (e.g. text form of a number)
vlen length of the value cookie magic callback cookie
typedef unsigned int rel_time_t
Time relative to server start. Smaller than time_t on 64-bit systems.
typedef struct _stritem item
Structure for storing items within memcached.
typedef struct conn conn
The structure representing a connection into memcached.
Enumeration Type Documentation
enum conn_states
Possible states of a connection.
Enumerator
conn_listening
the socket which listens for connections
conn_new_cmd
Prepare connection for next command
conn_waiting
waiting for a readable socket
conn_read
reading in a command line
conn_parse_cmd
try to parse a command from the input buffer
conn_write
writing out a simple response
conn_nread
reading in a fixed number of bytes
conn_swallow
swallowing unnecessary bytes w/o storing
conn_closing
closing this connection
conn_mwrite
writing out many items sequentially
conn_max_state
Max state value (used for assertion)
enum bin_substates
Enumerator
bin_no_state
bin_reading_set_header
bin_reading_cas_header
bin_read_set_value
bin_reading_get_key
bin_reading_stat
bin_reading_del_header
bin_reading_incr_header
bin_read_flush_exptime
bin_reading_sasl_auth
bin_reading_sasl_auth_data
bin_reading_touch_key
enum protocol
Enumerator
ascii_prot
binary_prot
negotiating_prot
enum network_transport
Enumerator
local_transport
tcp_transport
udp_transport
enum item_lock_types
Enumerator
ITEM_LOCK_GRANULAR
ITEM_LOCK_GLOBAL
enum store_item_type
Enumerator
NOT_STORED
STORED
EXISTS
NOT_FOUND
enum delta_result_type
Enumerator
OK
NON_NUMERIC
EOM
DELTA_ITEM_NOT_FOUND
DELTA_ITEM_CAS_MISMATCH
Function Documentation
void do_accept_new_conns (const booldo_accept)
References stats::accepting_conns, settings::backlog, stats::listen_disabled_num, conn::next, conn::sfd, STATS_LOCK(), and STATS_UNLOCK().
Referenced by accept_new_conns().
enum delta_result_type do_add_delta (conn *c, const char *key, const size_tnkey, const boolincr, const int64_tdelta, char *buf, uint64_t *cas, const uint32_thv)
References cache_lock, slab_stats::decr_hits, DELTA_ITEM_CAS_MISMATCH, DELTA_ITEM_NOT_FOUND, do_item_alloc(), do_item_get(), do_item_remove(), do_item_update(), EOM, _stritem::exptime, get_cas_id(), slab_stats::incr_hits, INCR_MAX_STORAGE_LEN, ITEM_data, ITEM_get_cas, ITEM_key, item_replace(), ITEM_set_cas, ITEM_suffix, MEMCACHED_COMMAND_DECR, MEMCACHED_COMMAND_INCR, thread_stats::mutex, mutex_unlock, _stritem::nbytes, _stritem::nkey, NON_NUMERIC, OK, _stritem::refcount, safe_strtoull(), conn::sfd, thread_stats::slab_stats, _stritem::slabs_clsid, LIBEVENT_THREAD::stats, conn::thread, and settings::use_cas.
Referenced by add_delta().
enum store_item_type do_store_item (item *item, intcomm, conn *c, const uint32_thv)
References conn::cas, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, do_item_alloc(), do_item_get(), do_item_link(), do_item_remove(), do_item_update(), EXISTS, _stritem::exptime, ITEM_data, ITEM_get_cas, ITEM_key, item_replace(), ITEM_suffix, thread_stats::mutex, _stritem::nbytes, _stritem::nkey, NOT_FOUND, NOT_STORED, NREAD_ADD, NREAD_APPEND, NREAD_CAS, NREAD_PREPEND, NREAD_REPLACE, thread_stats::slab_stats, _stritem::slabs_clsid, LIBEVENT_THREAD::stats, STORED, conn::thread, and settings::verbose.
Referenced by store_item().
conn* conn_new (const intsfd, const enum conn_statesinit_state, const intevent_flags, const intread_buffer_size, enum network_transporttransport, struct event_base *base)
References ascii_prot, binary_prot, settings::binding_protocol, conn::cmd, conn_add_to_freelist(), conn_from_freelist(), conn_listening, stats::conn_structs, stats::curr_conns, DATA_BUFFER_SIZE, conn::ev_flags, conn::event, conn::hdrbuf, conn::hdrsize, conn::icurr, conn::ileft, conn::ilist, conn::iov, IOV_LIST_INITIAL, conn::iovsize, conn::iovused, IS_UDP, conn::isize, conn::item, ITEM_LIST_INITIAL, MEMCACHED_CONN_ALLOCATE, MEMCACHED_CONN_CREATE, MSG_LIST_INITIAL, conn::msgcurr, conn::msglist, conn::msgsize, conn::msgused, negotiating_prot, conn::noreply, conn::protocol, conn::rbuf, conn::rbytes, conn::rcurr, conn::request_addr, conn::request_addr_size, conn::ritem, conn::rlbytes, conn::rsize, conn::sfd, settings::socketpath, conn::state, STATS_LOCK(), STATS_UNLOCK(), SUFFIX_LIST_INITIAL, conn::suffixcurr, conn::suffixleft, conn::suffixlist, conn::suffixsize, stats::total_conns, conn::transport, settings::verbose, conn::wbuf, conn::wbytes, conn::wcurr, conn::write_and_free, conn::write_and_go, and conn::wsize.
int daemonize (intnochdir, intnoclose)
Referenced by main().
void thread_init (intnthreads, struct event_base *main_base)
References LIBEVENT_DISPATCHER_THREAD::base, cache_lock, hashsize, LIBEVENT_THREAD::notify_receive_fd, LIBEVENT_THREAD::notify_send_fd, stats::reserved_fds, and LIBEVENT_DISPATCHER_THREAD::thread_id.
Referenced by main().
int dispatch_event_add (intthread, conn *c)
void dispatch_conn_new (intsfd, enum conn_statesinit_state, intevent_flags, intread_buffer_size, enum network_transporttransport)
References conn_queue_item::event_flags, conn_queue_item::init_state, MEMCACHED_CONN_DISPATCH, settings::num_threads, conn_queue_item::read_buffer_size, conn_queue_item::sfd, and conn_queue_item::transport.
enum delta_result_type add_delta (conn *c, const char *key, const size_tnkey, const intincr, const int64_tdelta, char *buf, uint64_t *cas)
References do_add_delta(), hash(), item_lock(), and item_unlock().
void accept_new_conns (const booldo_accept)
References conn_lock, and do_accept_new_conns().
conn* conn_from_freelist (void)
Referenced by conn_new().
bool conn_add_to_freelist (conn *c)
Referenced by conn_new().
int is_listen_thread (void)
References LIBEVENT_DISPATCHER_THREAD::thread_id.
item* item_alloc (char *key, size_tnkey, intflags, rel_time_texptime, intnbytes)
References do_item_alloc().
char* item_cachedump (const unsigned intslabs_clsid, const unsigned intlimit, unsigned int *bytes)
References cache_lock, do_item_cachedump(), and mutex_unlock.
void item_flush_expired (void)
References cache_lock, do_item_flush_expired(), and mutex_unlock.
item* item_get (const char *key, const size_tnkey)
References do_item_get(), hash(), item_lock(), and item_unlock().
item* item_touch (const char *key, const size_tnkey, uint32_texptime)
References do_item_touch(), hash(), item_lock(), and item_unlock().
int item_link (item *it)
References do_item_link(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_remove (item *it)
References do_item_remove(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
int item_replace (item *it, item *new_it, const uint32_thv)
References do_item_replace().
Referenced by do_add_delta(), and do_store_item().
void item_stats (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats(), and mutex_unlock.
Referenced by get_stats().
void item_stats_totals (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats_totals(), and mutex_unlock.
Referenced by get_stats().
void item_stats_sizes (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats_sizes(), and mutex_unlock.
Referenced by get_stats().
void item_unlink (item *it)
References do_item_unlink(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_update (item *it)
References do_item_update(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_lock_global (void)
void item_unlock_global (void)
References mutex_unlock.
void item_lock (uint32_thv)
References hashmask, hashpower, ITEM_LOCK_GRANULAR, and likely.
Referenced by add_delta(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item().
void* item_trylock (uint32_thv)
References hashmask, and hashpower.
Referenced by do_item_alloc().
void item_trylock_unlock (void *arg)
References mutex_unlock.
Referenced by do_item_alloc().
void item_unlock (uint32_thv)
References hashmask, hashpower, ITEM_LOCK_GRANULAR, likely, and mutex_unlock.
Referenced by add_delta(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item().
void switch_item_lock_type (enum item_lock_typestype)
References ITEM_LOCK_GLOBAL, ITEM_LOCK_GRANULAR, and settings::num_threads.
unsigned short refcount_incr (unsigned short *refcount)
References atomics_mutex, and mutex_unlock.
Referenced by do_item_alloc(), do_item_get(), and do_item_link().
unsigned short refcount_decr (unsigned short *refcount)
References atomics_mutex, and mutex_unlock.
Referenced by do_item_alloc(), and do_item_remove().
void STATS_LOCK (void)
Referenced by assoc_init(), conn_new(), do_accept_new_conns(), do_item_link(), do_item_unlink(), do_item_unlink_nolock(), get_stats(), stats_prefix_dump(), stats_prefix_record_delete(), stats_prefix_record_get(), and stats_prefix_record_set().
void STATS_UNLOCK (void)
Referenced by assoc_init(), conn_new(), do_accept_new_conns(), do_item_link(), do_item_unlink(), do_item_unlink_nolock(), get_stats(), stats_prefix_dump(), stats_prefix_record_delete(), stats_prefix_record_get(), and stats_prefix_record_set().
void threadlocal_stats_reset (void)
References thread_stats::auth_cmds, thread_stats::auth_errors, thread_stats::bytes_read, thread_stats::bytes_written, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, thread_stats::conn_yields, slab_stats::decr_hits, thread_stats::decr_misses, slab_stats::delete_hits, thread_stats::delete_misses, thread_stats::flush_cmds, thread_stats::get_cmds, slab_stats::get_hits, thread_stats::get_misses, slab_stats::incr_hits, thread_stats::incr_misses, MAX_NUMBER_OF_SLAB_CLASSES, stats::mutex, settings::num_threads, slab_stats::set_cmds, thread_stats::slab_stats, LIBEVENT_THREAD::stats, thread_stats::touch_cmds, slab_stats::touch_hits, and thread_stats::touch_misses.
void threadlocal_stats_aggregate (struct thread_stats *stats)
References thread_stats::auth_cmds, thread_stats::auth_errors, thread_stats::bytes_read, thread_stats::bytes_written, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, thread_stats::conn_yields, slab_stats::decr_hits, thread_stats::decr_misses, slab_stats::delete_hits, thread_stats::delete_misses, thread_stats::flush_cmds, thread_stats::get_cmds, slab_stats::get_hits, thread_stats::get_misses, slab_stats::incr_hits, thread_stats::incr_misses, MAX_NUMBER_OF_SLAB_CLASSES, thread_stats::mutex, settings::num_threads, slab_stats::set_cmds, thread_stats::slab_stats, LIBEVENT_THREAD::stats, thread_stats::touch_cmds, slab_stats::touch_hits, and thread_stats::touch_misses.
void slab_stats_aggregate (struct thread_stats *stats, struct slab_stats *out)
References slab_stats::cas_badval, slab_stats::cas_hits, slab_stats::decr_hits, slab_stats::delete_hits, slab_stats::get_hits, slab_stats::incr_hits, MAX_NUMBER_OF_SLAB_CLASSES, slab_stats::set_cmds, thread_stats::slab_stats, and slab_stats::touch_hits.
void append_stat (const char *name, ADD_STATadd_stats, conn *c, const char *fmt, ...)
References STAT_VAL_LEN.
enum store_item_type store_item (item *item, intcomm, conn *c)
References do_store_item(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
Variable Documentation
struct stats stats
exported globals
time_t process_started
Referenced by do_item_cachedump().
struct settings settings
volatile rel_time_t current_time
Referenced by do_item_alloc(), do_item_get(), do_item_link(), do_item_stats(), and do_item_update().
volatile int slab_rebalance_signal
Referenced by do_item_get(), and start_slab_maintenance_thread().
struct slab_rebalance slab_rebal
Referenced by do_item_get(), and start_slab_maintenance_thread().
Author
Generated automatically by Doxygen for memcached from the source code.