slabs.c
NAME
slabs.c -
SYNOPSIS
#include 'memcached.h'
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/signal.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <pthread.h>
Classes
struct slabclass_t
Macros
#define DEFAULT_SLAB_BULK_CHECK 1
Enumerations
enum move_status { MOVE_PASS =0, MOVE_DONE, MOVE_BUSY, MOVE_LOCKED }
Functions
unsigned int slabs_clsid (const size_t size)
void slabs_init (const size_t limit, const double factor, const bool prealloc)
bool get_stats (const char *stat_type, int nkey, ADD_STAT add_stats, void *c)
void * slabs_alloc (size_t size, unsigned int id)
void slabs_free (void *ptr, size_t size, unsigned int id)
void slabs_stats (ADD_STAT add_stats, void *c)
void slabs_adjust_mem_requested (unsigned int id, size_t old, size_t ntotal)
enum reassign_result_type slabs_reassign (int src, int dst)
void slabs_rebalancer_pause (void)
void slabs_rebalancer_resume (void)
int start_slab_maintenance_thread (void)
void stop_slab_maintenance_thread (void)
Variables
int slab_bulk_check = DEFAULT_SLAB_BULK_CHECK
Macro Definition Documentation
#define DEFAULT_SLAB_BULK_CHECK 1
Referenced by start_slab_maintenance_thread().
Enumeration Type Documentation
enum move_status
Enumerator
MOVE_PASS
MOVE_DONE
MOVE_BUSY
MOVE_LOCKED
Function Documentation
unsigned int slabs_clsid (const size_tsize)
Given object size, return id to use when allocating/freeing memory for object 0 means error: can't store such a large object
References POWER_SMALLEST.
Referenced by do_item_alloc(), do_item_cachedump(), and item_size_ok().
void slabs_init (const size_tlimit, const doublefactor, const boolprealloc)
Determines the chunk sizes and initializes the slab class descriptors accordingly.
References CHUNK_ALIGN_BYTES, settings::chunk_size, settings::item_size_max, slabclass_t::perslab, POWER_LARGEST, POWER_SMALLEST, slabclass_t::size, and settings::verbose.
Referenced by main().
bool get_stats (const char *stat_type, intnkey, ADD_STATadd_stats, void *c)
Return a datum for stats in binary protocol
References APPEND_STAT, stats::curr_bytes, stats::curr_items, item_stats(), item_stats_sizes(), item_stats_totals(), slabs_stats(), STATS_LOCK(), STATS_UNLOCK(), and stats::total_items.
void* slabs_alloc (const size_tsize, unsigned intid)
Allocate object of given length. 0 on error
Referenced by do_item_alloc().
void slabs_free (void *ptr, size_tsize, unsigned intid)
Free previously allocated object
Referenced by item_free().
void slabs_stats (ADD_STATadd_stats, void *c)
Fill buffer with stats
Referenced by get_stats().
void slabs_adjust_mem_requested (unsigned intid, size_told, size_tntotal)
Adjust the stats for memory requested
References slabclass_t::requested.
Referenced by do_item_alloc().
enum reassign_result_type slabs_reassign (intsrc, intdst)
References REASSIGN_RUNNING.
Referenced by do_item_alloc().
void slabs_rebalancer_pause (void)
void slabs_rebalancer_resume (void)
int start_slab_maintenance_thread (void)
References DEFAULT_SLAB_BULK_CHECK, slab_rebal, slab_rebalance_signal, and slab_rebalance::slab_start.
Referenced by main().
void stop_slab_maintenance_thread (void)
References cache_lock.
Variable Documentation
int slab_bulk_check = DEFAULT_SLAB_BULK_CHECK
Author
Generated automatically by Doxygen for memcached from the source code.