.TH "slab_stats" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slab_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memcached\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBset_cmds\fP"
.br
.ti -1c
.RI "uint64_t \fBget_hits\fP"
.br
.ti -1c
.RI "uint64_t \fBtouch_hits\fP"
.br
.ti -1c
.RI "uint64_t \fBdelete_hits\fP"
.br
.ti -1c
.RI "uint64_t \fBcas_hits\fP"
.br
.ti -1c
.RI "uint64_t \fBcas_badval\fP"
.br
.ti -1c
.RI "uint64_t \fBincr_hits\fP"
.br
.ti -1c
.RI "uint64_t \fBdecr_hits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stats stored per slab (and per thread)\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint64_t slab_stats::set_cmds"

.PP
Referenced by slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::get_hits"

.PP
Referenced by slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::touch_hits"

.PP
Referenced by slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::delete_hits"

.PP
Referenced by slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::cas_hits"

.PP
Referenced by do_store_item(), slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::cas_badval"

.PP
Referenced by do_store_item(), slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::incr_hits"

.PP
Referenced by do_add_delta(), slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.
.SS "uint64_t slab_stats::decr_hits"

.PP
Referenced by do_add_delta(), slab_stats_aggregate(), threadlocal_stats_aggregate(), and threadlocal_stats_reset()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
