.TH "stats.h" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stats.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstats_prefix_init\fP (void)"
.br
.ti -1c
.RI "void \fBstats_prefix_clear\fP (void)"
.br
.ti -1c
.RI "void \fBstats_prefix_record_get\fP (const char *key, const size_t nkey, const bool is_hit)"
.br
.ti -1c
.RI "void \fBstats_prefix_record_delete\fP (const char *key, const size_t nkey)"
.br
.ti -1c
.RI "void \fBstats_prefix_record_set\fP (const char *key, const size_t nkey)"
.br
.ti -1c
.RI "char * \fBstats_prefix_dump\fP (int *length)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void stats_prefix_init (void)"

.SS "void stats_prefix_clear (void)"

.PP
References _prefix_stats::next, _prefix_stats::prefix, and PREFIX_HASH_SIZE\&.
.SS "void stats_prefix_record_get (const char *key, const size_tnkey, const boolis_hit)"

.PP
References _prefix_stats::num_gets, _prefix_stats::num_hits, STATS_LOCK(), and STATS_UNLOCK()\&.
.SS "void stats_prefix_record_delete (const char *key, const size_tnkey)"

.PP
References _prefix_stats::num_deletes, STATS_LOCK(), and STATS_UNLOCK()\&.
.SS "void stats_prefix_record_set (const char *key, const size_tnkey)"

.PP
References _prefix_stats::num_sets, STATS_LOCK(), and STATS_UNLOCK()\&.
.SS "char* stats_prefix_dump (int *length)"

.PP
References _prefix_stats::next, _prefix_stats::num_deletes, _prefix_stats::num_gets, _prefix_stats::num_hits, _prefix_stats::num_sets, _prefix_stats::prefix, PREFIX_HASH_SIZE, STATS_LOCK(), and STATS_UNLOCK()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
