stats.c
NAME
stats.c -
SYNOPSIS
#include 'memcached.h'
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Classes
struct _prefix_stats
Macros
#define PREFIX_HASH_SIZE 256
Typedefs
typedef struct _prefix_stats PREFIX_STATS
Functions
void stats_prefix_init ()
void stats_prefix_clear ()
void stats_prefix_record_get (const char *key, const size_t nkey, const bool is_hit)
void stats_prefix_record_delete (const char *key, const size_t nkey)
void stats_prefix_record_set (const char *key, const size_t nkey)
char * stats_prefix_dump (int *length)
Macro Definition Documentation
#define PREFIX_HASH_SIZE 256
Referenced by stats_prefix_clear(), and stats_prefix_dump().
Typedef Documentation
typedef struct _prefix_stats PREFIX_STATS
Function Documentation
void stats_prefix_init (void)
void stats_prefix_clear (void)
References _prefix_stats::next, _prefix_stats::prefix, and PREFIX_HASH_SIZE.
void stats_prefix_record_get (const char *key, const size_tnkey, const boolis_hit)
References _prefix_stats::num_gets, _prefix_stats::num_hits, STATS_LOCK(), and STATS_UNLOCK().
void stats_prefix_record_delete (const char *key, const size_tnkey)
References _prefix_stats::num_deletes, STATS_LOCK(), and STATS_UNLOCK().
void stats_prefix_record_set (const char *key, const size_tnkey)
References _prefix_stats::num_sets, STATS_LOCK(), and STATS_UNLOCK().
char* stats_prefix_dump (int *length)
References _prefix_stats::next, _prefix_stats::num_deletes, _prefix_stats::num_gets, _prefix_stats::num_hits, _prefix_stats::num_sets, _prefix_stats::prefix, PREFIX_HASH_SIZE, STATS_LOCK(), and STATS_UNLOCK().
Author
Generated automatically by Doxygen for memcached from the source code.