.TH "testcase" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcase \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBTEST_FUNC\fP \fBfunction\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* testcase::description"

.PP
Referenced by main()\&.
.SS "\fBTEST_FUNC\fP testcase::function"

.PP
Referenced by main()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
