thread.c
NAME
thread.c -
SYNOPSIS
#include 'memcached.h'
#include <assert.h>
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
Classes
struct conn_queue_item
struct conn_queue
Macros
#define ITEMS_PER_ALLOC 64
#define hashsize(n) ((unsigned long int)1<<(n))
#define hashmask(n) (hashsize(n)-1)
Typedefs
typedef struct conn_queue_item CQ_ITEM
typedef struct conn_queue CQ
Functions
unsigned short refcount_incr (unsigned short *refcount)
unsigned short refcount_decr (unsigned short *refcount)
void item_lock_global (void)
void item_unlock_global (void)
void item_lock (uint32_t hv)
void * item_trylock (uint32_t hv)
void item_trylock_unlock (void *lock)
void item_unlock (uint32_t hv)
void switch_item_lock_type (enum item_lock_types type)
void accept_new_conns (const bool do_accept)
void dispatch_conn_new (int sfd, enum conn_states init_state, int event_flags, int read_buffer_size, enum network_transport transport)
int is_listen_thread ()
item * item_alloc (char *key, size_t nkey, int flags, rel_time_t exptime, int nbytes)
item * item_get (const char *key, const size_t nkey)
item * item_touch (const char *key, size_t nkey, uint32_t exptime)
int item_link (item *item)
void item_remove (item *item)
int item_replace (item *old_it, item *new_it, const uint32_t hv)
void item_unlink (item *item)
void item_update (item *item)
enum delta_result_type add_delta (conn *c, const char *key, const size_t nkey, int incr, const int64_t delta, char *buf, uint64_t *cas)
enum store_item_type store_item (item *item, int comm, conn *c)
void item_flush_expired ()
char * item_cachedump (unsigned int slabs_clsid, unsigned int limit, unsigned int *bytes)
void item_stats (ADD_STAT add_stats, void *c)
void item_stats_totals (ADD_STAT add_stats, void *c)
void item_stats_sizes (ADD_STAT add_stats, void *c)
void STATS_LOCK ()
void STATS_UNLOCK ()
void threadlocal_stats_reset (void)
void threadlocal_stats_aggregate (struct thread_stats *stats)
void slab_stats_aggregate (struct thread_stats *stats, struct slab_stats *out)
void thread_init (int nthreads, struct event_base *main_base)
Variables
pthread_mutex_t cache_lock
pthread_mutex_t conn_lock = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t atomics_mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
#define ITEMS_PER_ALLOC 64
#define hashsize(n) ((unsigned long int)1<<(n))
Referenced by thread_init().
#define hashmask(n) (hashsize(n)-1)
Referenced by item_lock(), item_trylock(), and item_unlock().
Typedef Documentation
typedef struct conn_queue_item CQ_ITEM
typedef struct conn_queue CQ
Function Documentation
unsigned short refcount_incr (unsigned short *refcount)
References atomics_mutex, and mutex_unlock.
Referenced by do_item_alloc(), do_item_get(), and do_item_link().
unsigned short refcount_decr (unsigned short *refcount)
References atomics_mutex, and mutex_unlock.
Referenced by do_item_alloc(), and do_item_remove().
void item_lock_global (void)
void item_unlock_global (void)
References mutex_unlock.
void item_lock (uint32_thv)
References hashmask, hashpower, ITEM_LOCK_GRANULAR, and likely.
Referenced by add_delta(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item().
void* item_trylock (uint32_thv)
References hashmask, and hashpower.
Referenced by do_item_alloc().
void item_trylock_unlock (void *lock)
References mutex_unlock.
Referenced by do_item_alloc().
void item_unlock (uint32_thv)
References hashmask, hashpower, ITEM_LOCK_GRANULAR, likely, and mutex_unlock.
Referenced by add_delta(), item_get(), item_link(), item_remove(), item_touch(), item_unlink(), item_update(), and store_item().
void switch_item_lock_type (enum item_lock_typestype)
References ITEM_LOCK_GLOBAL, ITEM_LOCK_GRANULAR, and settings::num_threads.
void accept_new_conns (const booldo_accept)
References conn_lock, and do_accept_new_conns().
void dispatch_conn_new (intsfd, enum conn_statesinit_state, intevent_flags, intread_buffer_size, enum network_transporttransport)
References conn_queue_item::event_flags, conn_queue_item::init_state, MEMCACHED_CONN_DISPATCH, settings::num_threads, conn_queue_item::read_buffer_size, conn_queue_item::sfd, and conn_queue_item::transport.
int is_listen_thread (void)
References LIBEVENT_DISPATCHER_THREAD::thread_id.
item* item_alloc (char *key, size_tnkey, intflags, rel_time_texptime, intnbytes)
References do_item_alloc().
item* item_get (const char *key, const size_tnkey)
References do_item_get(), hash(), item_lock(), and item_unlock().
item* item_touch (const char *key, size_tnkey, uint32_texptime)
References do_item_touch(), hash(), item_lock(), and item_unlock().
int item_link (item *item)
References do_item_link(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_remove (item *item)
References do_item_remove(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
int item_replace (item *old_it, item *new_it, const uint32_thv)
References do_item_replace().
Referenced by do_add_delta(), and do_store_item().
void item_unlink (item *item)
References do_item_unlink(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_update (item *item)
References do_item_update(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
enum delta_result_type add_delta (conn *c, const char *key, const size_tnkey, intincr, const int64_tdelta, char *buf, uint64_t *cas)
References do_add_delta(), hash(), item_lock(), and item_unlock().
enum store_item_type store_item (item *item, intcomm, conn *c)
References do_store_item(), hash(), ITEM_key, item_lock(), item_unlock(), and _stritem::nkey.
void item_flush_expired (void)
References cache_lock, do_item_flush_expired(), and mutex_unlock.
char* item_cachedump (unsigned intslabs_clsid, unsigned intlimit, unsigned int *bytes)
References cache_lock, do_item_cachedump(), and mutex_unlock.
void item_stats (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats(), and mutex_unlock.
Referenced by get_stats().
void item_stats_totals (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats_totals(), and mutex_unlock.
Referenced by get_stats().
void item_stats_sizes (ADD_STATadd_stats, void *c)
References cache_lock, do_item_stats_sizes(), and mutex_unlock.
Referenced by get_stats().
void STATS_LOCK (void)
Referenced by assoc_init(), conn_new(), do_accept_new_conns(), do_item_link(), do_item_unlink(), do_item_unlink_nolock(), get_stats(), stats_prefix_dump(), stats_prefix_record_delete(), stats_prefix_record_get(), and stats_prefix_record_set().
void STATS_UNLOCK (void)
Referenced by assoc_init(), conn_new(), do_accept_new_conns(), do_item_link(), do_item_unlink(), do_item_unlink_nolock(), get_stats(), stats_prefix_dump(), stats_prefix_record_delete(), stats_prefix_record_get(), and stats_prefix_record_set().
void threadlocal_stats_reset (void)
References thread_stats::auth_cmds, thread_stats::auth_errors, thread_stats::bytes_read, thread_stats::bytes_written, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, thread_stats::conn_yields, slab_stats::decr_hits, thread_stats::decr_misses, slab_stats::delete_hits, thread_stats::delete_misses, thread_stats::flush_cmds, thread_stats::get_cmds, slab_stats::get_hits, thread_stats::get_misses, slab_stats::incr_hits, thread_stats::incr_misses, MAX_NUMBER_OF_SLAB_CLASSES, stats::mutex, settings::num_threads, slab_stats::set_cmds, thread_stats::slab_stats, LIBEVENT_THREAD::stats, thread_stats::touch_cmds, slab_stats::touch_hits, and thread_stats::touch_misses.
void threadlocal_stats_aggregate (struct thread_stats *stats)
References thread_stats::auth_cmds, thread_stats::auth_errors, thread_stats::bytes_read, thread_stats::bytes_written, slab_stats::cas_badval, slab_stats::cas_hits, thread_stats::cas_misses, thread_stats::conn_yields, slab_stats::decr_hits, thread_stats::decr_misses, slab_stats::delete_hits, thread_stats::delete_misses, thread_stats::flush_cmds, thread_stats::get_cmds, slab_stats::get_hits, thread_stats::get_misses, slab_stats::incr_hits, thread_stats::incr_misses, MAX_NUMBER_OF_SLAB_CLASSES, thread_stats::mutex, settings::num_threads, slab_stats::set_cmds, thread_stats::slab_stats, LIBEVENT_THREAD::stats, thread_stats::touch_cmds, slab_stats::touch_hits, and thread_stats::touch_misses.
void slab_stats_aggregate (struct thread_stats *stats, struct slab_stats *out)
References slab_stats::cas_badval, slab_stats::cas_hits, slab_stats::decr_hits, slab_stats::delete_hits, slab_stats::get_hits, slab_stats::incr_hits, MAX_NUMBER_OF_SLAB_CLASSES, slab_stats::set_cmds, thread_stats::slab_stats, and slab_stats::touch_hits.
void thread_init (intnthreads, struct event_base *main_base)
References LIBEVENT_DISPATCHER_THREAD::base, cache_lock, hashsize, LIBEVENT_THREAD::notify_receive_fd, LIBEVENT_THREAD::notify_send_fd, stats::reserved_fds, and LIBEVENT_DISPATCHER_THREAD::thread_id.
Referenced by main().
Variable Documentation
pthread_mutex_t cache_lock
Referenced by do_add_delta(), do_item_alloc(), do_item_link(), do_item_unlink(), do_item_update(), item_cachedump(), item_flush_expired(), item_stats(), item_stats_evictions(), item_stats_reset(), item_stats_sizes(), item_stats_totals(), stop_assoc_maintenance_thread(), stop_slab_maintenance_thread(), and thread_init().
pthread_mutex_t conn_lock = PTHREAD_MUTEX_INITIALIZER
Referenced by accept_new_conns().
pthread_mutex_t atomics_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by refcount_decr(), and refcount_incr().
Author
Generated automatically by Doxygen for memcached from the source code.