.TH "token_s" 3 "Wed Apr 3 2013" "Version 0.8" "memcached" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* token_s::value"

.SS "size_t token_s::length"


.SH "Author"
.PP 
Generated automatically by Doxygen for memcached from the source code\&.
